import { Injectable } from '@angular/core';
import { Observable, of, tap } from 'rxjs';
import { ProjetoRequest, ProjetoResponse, ProjetoPageResponse } from '../models/projeto';

@Injectable({ providedIn: 'root' })
export class ProjetoService {
  // TODO: trocar para HttpClient quando o backend estiver disponível
  // private readonly url = 'http://localhost:8080/api/projetos';

  private getStorage(): ProjetoResponse[] {
    const raw = localStorage.getItem('projetos_mock');
    return raw ? JSON.parse(raw) : [];
  }

  private setStorage(projetos: ProjetoResponse[]) {
    localStorage.setItem('projetos_mock', JSON.stringify(projetos));
  }

  criar(projeto: ProjetoRequest): Observable<ProjetoResponse> {
    const projetos = this.getStorage();
    const novo: ProjetoResponse = {
      ...projeto,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    projetos.push(novo);
    this.setStorage(projetos);
    return of(novo);
  }

  listar(page = 0, size = 20): Observable<ProjetoPageResponse> {
    const todos = this.getStorage();
    const start = page * size;
    const content = todos.slice(start, start + size);
    return of({
      content,
      page,
      size,
      totalElements: todos.length,
      totalPages: Math.ceil(todos.length / size) || 1,
    });
  }

  obter(id: string): Observable<ProjetoResponse> {
    const projeto = this.getStorage().find(p => p.id === id);
    return of(projeto!);
  }

  atualizar(id: string, projeto: ProjetoRequest): Observable<ProjetoResponse> {
    const projetos = this.getStorage();
    const idx = projetos.findIndex(p => p.id === id);
    if (idx >= 0) {
      projetos[idx] = { ...projetos[idx], ...projeto, updatedAt: new Date().toISOString() };
      this.setStorage(projetos);
      return of(projetos[idx]);
    }
    return of(null as any);
  }

  seedSeNecessario(): void {
    if (this.getStorage().length >= 8) return;
    localStorage.removeItem('projetos_mock');

    const projetos: ProjetoRequest[] = [
      {
        nome: 'Portal de Serviços Digitais',
        sigla: 'PSD',
        areaSolicitante: 'GECOR',
        areaExecutora: 'Divisão de Sistemas e Soluções de TIC',
        descricao: 'Implantação de portal unificado para prestação de serviços digitais ao cidadão, integrando sistemas legados e novos módulos.',
        objetivo: 'Ampliar o acesso digital aos serviços públicos, reduzindo atendimento presencial.',
        justificativa: 'O atendimento presencial representa alto custo operacional e baixa satisfação dos usuários.',
        beneficiosEsperados: 'Redução de custos operacionais, agilidade no atendimento e melhoria da experiência do cidadão.',
        po: 'Luciane Reis',
        scrumMaster: 'Ana Carolina Souza',
        patrocinador: 'Roberto Campos',
        gerenteResponsavel: 'Fernanda Lima',
        dataInicioPrevista: '2024-05-01',
        dataConclusaoPrevista: '2027-02-28',
        orcamentoEstimado: 2100000,
        custoRealizado: 1740000,
        qtdProprios: 4,
        qtdTerceiros: 6,
        priorizadoPdtic: true,
        inovador: false,
        tipo: 'PRODUTO_TI',
        faseCiclo: 'EXECUCAO',
        prazoQuadrante: 'NO_PRAZO',
        custoQuadrante: 'ATENCAO',
        objetivoEstrategico: 'Ampliar e melhorar os serviços digitais',
        iniciativaEstrategica: 'Modernização do portal de serviços',
        indicadorEstrategico: '% de serviços digitais disponibilizados',
        fases: [
          { nome: 'Descoberta', duracaoMeses: 3 },
          { nome: 'MVP', duracaoMeses: 6 },
          { nome: 'Produção', duracaoMeses: 12 },
        ],
        status: 'APROVADO',
      },
      {
        nome: 'Monitoração de ITAA (Integra)',
        sigla: 'ITAA',
        areaSolicitante: 'GERED',
        areaExecutora: 'Divisão de Infraestrutura e Segurança',
        descricao: 'Sistema de monitoração integrada de infraestrutura de TI e ativos de automação.',
        objetivo: 'Garantir disponibilidade e desempenho da infraestrutura de TIC.',
        justificativa: 'Falta de visibilidade sobre o estado dos ativos compromete a continuidade dos serviços.',
        beneficiosEsperados: 'Aumento da disponibilidade dos serviços e redução de incidentes.',
        po: 'Anny Delgado',
        scrumMaster: 'Thiago Almeida',
        patrocinador: 'Patrícia Mendes',
        gerenteResponsavel: 'Lucas Oliveira',
        dataInicioPrevista: '2025-06-02',
        dataConclusaoPrevista: '2027-12-28',
        orcamentoEstimado: 3000000,
        custoRealizado: 1610000,
        qtdProprios: 3,
        qtdTerceiros: 9,
        priorizadoPdtic: true,
        inovador: false,
        tipo: 'SOLUCAO_TECNOLOGICA',
        faseCiclo: 'EXECUCAO',
        prazoQuadrante: 'NO_PRAZO',
        custoQuadrante: 'NO_CUSTO',
        objetivoEstrategico: 'Modernizar a infraestrutura tecnológica',
        iniciativaEstrategica: 'Migração para infraestrutura em nuvem',
        indicadorEstrategico: 'Índice de maturidade de governança de TIC',
        fases: [
          { nome: 'Planejamento', duracaoMeses: 2 },
          { nome: 'Implantação', duracaoMeses: 8 },
          { nome: 'Operação Assistida', duracaoMeses: 4 },
        ],
        status: 'APROVADO',
      },
      {
        nome: 'PSIM 4.0',
        sigla: 'PSIM',
        areaSolicitante: 'GELOP',
        areaExecutora: 'Divisão de Sistemas e Soluções de TIC',
        descricao: 'Evolução da plataforma de segurança integrada com módulos de IA para detecção de ameaças.',
        objetivo: 'Fortalecer a segurança cibernética e proteção de dados.',
        justificativa: 'A infraestrutura atual apresenta defasagem tecnológica, comprometendo a segurança.',
        beneficiosEsperados: 'Conformidade com políticas de segurança e redução de incidentes.',
        po: 'Michael Lago',
        scrumMaster: 'Claudia Grazielle',
        patrocinador: 'Roberto Campos',
        gerenteResponsavel: 'Fernanda Lima',
        dataInicioPrevista: '2026-02-02',
        dataConclusaoPrevista: '2028-10-31',
        orcamentoEstimado: 14600000,
        custoRealizado: 710000,
        qtdProprios: 3,
        qtdTerceiros: 1,
        priorizadoPdtic: true,
        inovador: true,
        justificativaInovador: 'Uso de IA generativa para correlação de eventos de segurança em tempo real.',
        tipo: 'PRODUTO_TI',
        faseCiclo: 'PLANEJAMENTO',
        prazoQuadrante: 'NO_PRAZO',
        custoQuadrante: 'NO_CUSTO',
        objetivoEstrategico: 'Fortalecer a segurança cibernética e proteção de dados',
        iniciativaEstrategica: 'Implantação do SOC (Security Operations Center)',
        indicadorEstrategico: 'Tempo médio de resposta a incidentes de segurança',
        fases: [
          { nome: 'PoC', duracaoMeses: 4 },
          { nome: 'MVP', duracaoMeses: 6 },
          { nome: 'Produção', duracaoMeses: 12 },
          { nome: 'Sustentação', duracaoMeses: 6 },
        ],
        status: 'APROVADO',
      },
      {
        nome: 'Kodiak',
        sigla: 'KDK',
        areaSolicitante: 'GESIT',
        areaExecutora: 'Divisão de Governança e Gestão de TIC',
        descricao: 'Plataforma de gestão de contratos e fornecedores de TIC com dashboards analíticos.',
        objetivo: 'Centralizar a gestão de contratos para maior transparência e controle.',
        justificativa: 'Controle descentralizado em planilhas dificulta a visibilidade dos contratos vigentes.',
        beneficiosEsperados: 'Maior transparência e rastreabilidade na gestão de contratos.',
        po: 'Guilherme Reis',
        scrumMaster: 'Ana Carolina Souza',
        patrocinador: 'Patrícia Mendes',
        gerenteResponsavel: 'Thiago Almeida',
        dataInicioPrevista: '2025-04-14',
        dataConclusaoPrevista: '2028-04-30',
        orcamentoEstimado: 1800000,
        custoRealizado: 983000,
        qtdProprios: 2,
        qtdTerceiros: 3,
        priorizadoPdtic: false,
        inovador: false,
        tipo: 'PRODUTO_TI',
        faseCiclo: 'EXECUCAO',
        prazoQuadrante: 'NO_PRAZO',
        custoQuadrante: 'NO_CUSTO',
        objetivoEstrategico: 'Aprimorar a governança e gestão de TIC',
        iniciativaEstrategica: 'Implantação do SIGOV-TIC',
        indicadorEstrategico: '% de conformidade com a IN SGD/ME nº 94',
        fases: [
          { nome: 'Levantamento', duracaoMeses: 3 },
          { nome: 'Desenvolvimento', duracaoMeses: 10 },
        ],
        status: 'APROVADO',
      },
      {
        nome: 'Consignado Digital',
        sigla: 'CSD',
        areaSolicitante: 'GEREL',
        areaExecutora: 'Coordenação de Desenvolvimento',
        descricao: 'Digitalização completa do processo de consignado com assinatura eletrônica.',
        objetivo: 'Eliminar papel no processo de consignado e acelerar aprovações.',
        justificativa: 'Processo manual leva em média 15 dias e gera alto custo operacional.',
        beneficiosEsperados: 'Redução de 15 para 2 dias no tempo de processamento.',
        po: 'Luiz Otavio',
        scrumMaster: 'Lucas Oliveira',
        patrocinador: 'Roberto Campos',
        gerenteResponsavel: 'Fernanda Lima',
        dataInicioPrevista: '2025-07-18',
        dataConclusaoPrevista: '2028-01-18',
        orcamentoEstimado: 6500000,
        custoRealizado: 1780000,
        qtdProprios: 3,
        qtdTerceiros: 13,
        priorizadoPdtic: true,
        inovador: false,
        tipo: 'SOLUCAO_TECNOLOGICA',
        faseCiclo: 'EXECUCAO',
        prazoQuadrante: 'ATENCAO',
        custoQuadrante: 'ATENCAO',
        objetivoEstrategico: 'Ampliar e melhorar os serviços digitais',
        iniciativaEstrategica: 'Modernização do portal de serviços',
        indicadorEstrategico: 'Índice de satisfação dos usuários de TIC',
        fases: [
          { nome: 'Análise', duracaoMeses: 4 },
          { nome: 'Sprint 1-4', duracaoMeses: 8 },
          { nome: 'Homologação', duracaoMeses: 3 },
        ],
        status: 'APROVADO',
      },
      {
        nome: 'Kaiu — Kit Pré-Ajuizamento',
        sigla: 'KAIU',
        areaSolicitante: 'GECOB',
        areaExecutora: 'Divisão de Sistemas e Soluções de TIC',
        descricao: 'Automação do processo de pré-ajuizamento com triagem inteligente de documentos.',
        objetivo: 'Reduzir o tempo de triagem e preparação de processos judiciais.',
        justificativa: 'Volume crescente de processos impossibilita triagem manual eficiente.',
        beneficiosEsperados: 'Redução de 60% no tempo de triagem de processos.',
        po: 'Vitor Viana',
        scrumMaster: 'Thiago Almeida',
        patrocinador: 'Patrícia Mendes',
        gerenteResponsavel: 'Lucas Oliveira',
        dataInicioPrevista: '2026-05-04',
        dataConclusaoPrevista: '2027-01-29',
        orcamentoEstimado: 1270000,
        custoRealizado: 205200,
        qtdProprios: 2,
        qtdTerceiros: 3,
        priorizadoPdtic: false,
        inovador: true,
        justificativaInovador: 'Uso de NLP para classificação automática de peças processuais.',
        tipo: 'PRODUTO_TI',
        faseCiclo: 'PLANEJAMENTO',
        prazoQuadrante: 'NO_PRAZO',
        custoQuadrante: 'NO_CUSTO',
        objetivoEstrategico: 'Promover a inovação e transformação digital',
        iniciativaEstrategica: 'Capacitação em competências digitais',
        indicadorEstrategico: '% de projetos alinhados ao PDTIC',
        fases: [
          { nome: 'PoC', duracaoMeses: 2 },
          { nome: 'MVP', duracaoMeses: 4 },
        ],
        status: 'AGUARDANDO_APROVACAO',
      },
      {
        nome: 'Adequação à LGPD',
        sigla: 'LGPD-TIC',
        areaSolicitante: 'Coordenação-Geral de TIC',
        areaExecutora: 'Divisão de Governança e Gestão de TIC',
        descricao: 'Programa de adequação dos sistemas e processos de TIC à Lei Geral de Proteção de Dados.',
        objetivo: 'Garantir conformidade total com a LGPD em todos os sistemas.',
        justificativa: 'Auditoria identificou 23 sistemas sem mapeamento de dados pessoais.',
        beneficiosEsperados: 'Conformidade legal e redução de riscos de sanções.',
        po: 'Natan Heringer',
        scrumMaster: 'Ana Carolina Souza',
        patrocinador: 'Roberto Campos',
        gerenteResponsavel: 'Murilo Henrique',
        dataInicioPrevista: '2026-01-15',
        dataConclusaoPrevista: '2026-12-30',
        orcamentoEstimado: 850000,
        custoRealizado: 320000,
        qtdProprios: 2,
        qtdTerceiros: 2,
        priorizadoPdtic: true,
        inovador: false,
        tipo: 'SOLUCAO_TECNOLOGICA',
        faseCiclo: 'EXECUCAO',
        prazoQuadrante: 'ATRASADO',
        custoQuadrante: 'ATENCAO',
        objetivoEstrategico: 'Fortalecer a segurança cibernética e proteção de dados',
        iniciativaEstrategica: 'Adequação à LGPD',
        indicadorEstrategico: '% de conformidade com a IN SGD/ME nº 94',
        fases: [
          { nome: 'Diagnóstico', duracaoMeses: 3 },
          { nome: 'Implementação', duracaoMeses: 6 },
          { nome: 'Auditoria', duracaoMeses: 2 },
        ],
        status: 'APROVADO',
      },
      {
        nome: 'Modernização da Infraestrutura de Rede',
        sigla: 'MIR',
        areaSolicitante: 'Diretoria de Tecnologia da Informação',
        areaExecutora: 'Divisão de Infraestrutura e Segurança',
        descricao: 'Substituição de ativos defasados e ampliação da capacidade da rede corporativa.',
        objetivo: 'Garantir disponibilidade e desempenho da infraestrutura de rede.',
        justificativa: '40% dos switches têm mais de 8 anos de uso e estão fora de suporte.',
        beneficiosEsperados: 'Aumento de 99.5% para 99.95% de disponibilidade da rede.',
        po: 'Murilo Henrique',
        scrumMaster: 'Thiago Almeida',
        patrocinador: 'Patrícia Mendes',
        gerenteResponsavel: 'Lucas Oliveira',
        dataInicioPrevista: '2025-03-10',
        dataConclusaoPrevista: '2027-06-30',
        orcamentoEstimado: 5200000,
        custoRealizado: 2100000,
        qtdProprios: 5,
        qtdTerceiros: 8,
        priorizadoPdtic: true,
        inovador: false,
        tipo: 'SOLUCAO_TECNOLOGICA',
        faseCiclo: 'EXECUCAO',
        prazoQuadrante: 'NO_PRAZO',
        custoQuadrante: 'NO_CUSTO',
        objetivoEstrategico: 'Modernizar a infraestrutura tecnológica',
        iniciativaEstrategica: 'Migração para infraestrutura em nuvem',
        indicadorEstrategico: 'Índice de maturidade de governança de TIC',
        fases: [
          { nome: 'Licitação', duracaoMeses: 6 },
          { nome: 'Implantação Fase 1', duracaoMeses: 8 },
          { nome: 'Implantação Fase 2', duracaoMeses: 6 },
        ],
        status: 'APROVADO',
      },
      {
        nome: 'Sistema de Governança de TIC',
        sigla: 'SIGOV-TIC',
        areaSolicitante: 'Coordenação-Geral de TIC',
        areaExecutora: 'Divisão de Sistemas e Soluções de TIC',
        descricao: 'Desenvolvimento de sistema web para gestão do portfólio de projetos de TIC, permitindo cadastro, acompanhamento e governança.',
        objetivo: 'Centralizar a governança de TIC em uma plataforma única.',
        justificativa: 'Atualmente o controle é feito em planilhas, sem vínculo formal com o PDTIC.',
        beneficiosEsperados: 'Maior transparência na gestão de TIC e conformidade com a IN SGD/ME nº 94.',
        po: 'Natan Heringer',
        scrumMaster: 'Murilo Henrique',
        patrocinador: 'Roberto Campos',
        gerenteResponsavel: 'Natan Heringer',
        dataInicioPrevista: '2026-08-01',
        dataConclusaoPrevista: '2027-04-30',
        orcamentoEstimado: 420000,
        custoRealizado: 0,
        qtdProprios: 2,
        qtdTerceiros: 0,
        priorizadoPdtic: true,
        inovador: false,
        tipo: 'PRODUTO_TI',
        faseCiclo: 'EXECUCAO',
        prazoQuadrante: 'NO_PRAZO',
        custoQuadrante: 'NO_CUSTO',
        objetivoEstrategico: 'Aprimorar a governança e gestão de TIC',
        iniciativaEstrategica: 'Implantação do SIGOV-TIC',
        indicadorEstrategico: '% de projetos alinhados ao PDTIC',
        fases: [
          { nome: 'MVP', duracaoMeses: 3 },
          { nome: 'Produção', duracaoMeses: 5 },
        ],
        status: 'APROVADO',
      },
      {
        nome: 'Data Lake Corporativo',
        sigla: 'DLC',
        areaSolicitante: 'Secretaria de Governança Digital',
        areaExecutora: 'Coordenação de Desenvolvimento',
        descricao: 'Criação de repositório centralizado de dados para analytics e inteligência de negócio.',
        objetivo: 'Permitir análise de dados cross-sistema para tomada de decisão baseada em evidências.',
        justificativa: 'Dados isolados em silos impedem análise integrada e geram retrabalho.',
        beneficiosEsperados: 'Redução de 70% no tempo de geração de relatórios gerenciais.',
        po: 'Fernanda Lima',
        scrumMaster: 'Claudia Grazielle',
        patrocinador: 'Roberto Campos',
        gerenteResponsavel: 'Thiago Almeida',
        dataInicioPrevista: '2026-09-01',
        dataConclusaoPrevista: '2028-03-31',
        orcamentoEstimado: 3800000,
        custoRealizado: 0,
        qtdProprios: 3,
        qtdTerceiros: 5,
        priorizadoPdtic: true,
        inovador: true,
        justificativaInovador: 'Uso de arquitetura lakehouse com processamento distribuído.',
        tipo: 'PRODUTO_TI',
        faseCiclo: 'PLANEJAMENTO',
        prazoQuadrante: 'NO_PRAZO',
        custoQuadrante: 'NO_CUSTO',
        objetivoEstrategico: 'Promover a inovação e transformação digital',
        iniciativaEstrategica: 'Capacitação em competências digitais',
        indicadorEstrategico: 'Índice de maturidade de governança de TIC',
        fases: [
          { nome: 'Arquitetura', duracaoMeses: 3 },
          { nome: 'Ingestão', duracaoMeses: 6 },
          { nome: 'Analytics', duracaoMeses: 6 },
        ],
        status: 'RASCUNHO',
      },
    ];

    projetos.forEach(p => {
      this.criar(p).subscribe();
    });
  }
}
